Repository kaltura/kaltura-player-js, pull requests merged in 2018-06, with the labels that each got.

#128 feat(FEC-8281): support jsonP redirect for OTT
  src/common/utils/external-stream-redirect-helper.js
Labels: Type: Feature

#130 feat(FEC-8046): 360 support
  src/common/plugins/plugins-config.js
  src/common/plugins/plugins-config.json
  src/common/ui-wrapper.js
  src/kaltura-player.js
  test/src/common/utils/ui-wrapper.spec.js
Labels: Priority: High, Type: Feature

#132 feat(FEC-8331): expose the anonymous flag on session object
  package.json
  src/common/plugins/plugins-config.js
  src/common/plugins/plugins-config.json
  yarn.lock
Labels: Type: Feature

#134 fix(FEC-8349): OTT analytics - no event send for logged user
  src/common/plugins/plugins-config.js
  src/common/utils/evaluate.js
  test/src/common/utils/ui-wrapper.spec.js
Labels: Priority: High, Type: Bug

#135 fix(FEC-7971): change media doesn't work after a critical error
  src/common/ui-wrapper.js
  src/kaltura-player.js
Labels: Priority: High, Type: Bug

#137 fix(FEC-8356): pass player version string via config
  src/common/plugins/plugins-config.json
Labels: Type: Bug
