Repository kaltura/kaltura-player-js, pull requests merged in 2018-11, with the labels that each got.

#168 fix(FEC-8588): large play button displayed for a sec before the next item is playing
  samples/ovp/playlist-by-entry-list.html
  src/common/playlist/playlist-manager.js
  src/kaltura-player.js
Labels: Priority: High, Type: Bug

#172 fix(FEC-8588): large play button displayed for a sec before the next item is playing
  src/common/playlist/playlist-manager.js
Labels: Priority: High, Type: Bug

#171 fix(FEC-8581): playlist by config, no playlist buttons in first video
  samples/ovp/playlist-by-config.html
  samples/ovp/playlist-by-entry-list.html
  samples/ovp/playlist-by-id.html
  src/common/playlist/playlist-manager.js
  src/kaltura-player.js
Labels: Priority: High, Type: Bug

#173 docs: playlist
  docs/api.md
  flow-typed/types/playlist-config.js
  flow-typed/types/playlist-countdown-options.js
  flow-typed/types/playlist-item-config.js
  flow-typed/types/playlist-metadata.js
  flow-typed/types/playlist-options.js
  src/common/playlist/index.js
  src/common/playlist/playlist-event-type.js
  src/common/playlist/playlist-item.js
  src/common/playlist/playlist-manager.js
  src/index.js
Labels: Type: Docs

#175 fix(FEC-8689): PLAYLIST_ITEM_CHANGED event fired before item has been changed
  src/common/playlist/playlist-manager.js
Labels: Priority: High, Type: Bug

#177 fix(FEC-8698): when ui is disabled, playNext() called even when playlist isn't configured
  samples/ovp/cast.html
  src/common/playlist/playlist-manager.js
  src/kaltura-player.js
Labels: Priority: High, Type: Bug

#179 fix(FEC-8713): playlist by config not playing
  src/common/playlist/playlist-manager.js
Labels: Priority: High, Type: Bug

#180 chore: typo in pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Priority: Low
