Repository kaltura/kaltura-player-js, pull requests merged in 2018-07, with the labels that each got.

#139 feat(FEC-8364): support adding evaluated expressions also on player setup and configure API
  src/common/plugins/plugins-config-store.js
  src/common/plugins/plugins-config.js
  src/common/plugins/plugins-config.json
  src/kaltura-player.js
Labels: Type: Feature

#143 fix(FEC-8375): plugins data not evaluated
  src/common/plugins/plugins-config.js
Labels: Type: Bug

#136 fix(FEC-8355): on change media the config hold the old seekbar configuration
  src/common/ui-wrapper.js
  src/kaltura-player.js
  test/src/common/utils/ui-wrapper.spec.js
Labels: Type: Bug

#144 fix(FEC-8382): stereo icon displayed on iPhone, even if VR plugin disabled
  src/common/ui-wrapper.js
Labels: Priority: High, Type: Bug
