Repository kaltura/kaltura-player-js, pull requests merged in 2018-12, with the labels that each got.

#181 fix(FEC-8714): 'onclick' handler for iOS is not needed
  src/common/utils/setup-helpers.js
  src/setup.js
Labels: Priority: Medium, Type: Bug

#185 fix(FEC-8726): kalturaPlayer.config api is broken while casting
  docs/api.md
  src/common/cast/base-remote-player.js
  src/common/cast/remote-player.js
Labels: Priority: High, Type: Bug

#182 chore(FEC-8715): update docs regarding default text track labeling
  docs/managing-tracks.md
Labels: Priority: Medium, Type: Docs

#187 feat(FEC-8507): update hlsjs version to 0.12.0
  package.json
Labels: Priority: Medium, Type: Feature, Type: Maintenance

#186 feat(FEC-8705): playlist - OTT support
  docs/api.md
  flow-typed/types/kaltura-player-options.js
  flow-typed/types/playlist-config.js
  flow-typed/types/playlist-countdown-options.js
  flow-typed/types/playlist-item-config.js
  flow-typed/types/playlist-metadata.js
  flow-typed/types/playlist-options.js
  flow-typed/types/playlist.js
  package.json
  samples/ovp/playlist-by-id.html
  src/common/playlist/playlist-item.js
  src/common/playlist/playlist-manager.js
  src/common/playlist/playlist.js
  src/kaltura-player.js
  test/src/common/playlist/playlist-manager.spec.js
  test/src/kaltura-player.spec.js
  test/src/mock-data/media.js
  test/src/mock-data/playlist.js
  yarn.lock
Labels: Priority: High, Type: Feature

#192 fix(FEC-8780): captions not shown after seek
  package.json
  yarn.lock
Labels: Priority: High, Type: Bug
