Repository kaltura/kaltura-player-js, pull requests merged in 2019-07, with the labels that each got.

#250 feat(FEC-9145): support non sibling video tags
  src/common/utils/setup-helpers.js
  test/src/common/utils/setup-helpers.spec.js
Labels: Priority: High, Type: Feature

#252 feat(FEC-9156): getting bumper from playback context
  src/kaltura-player.js
Labels: Priority: High, Type: Feature

#254 feat(FEC-9227): support reInit of MSE
  src/common/utils/setup-helpers.js
Labels: Type: Feature

#258 fix: useNativeTextTrack doesn't change to true by default on MacOS
  package.json
  src/common/utils/setup-helpers.js
  yarn.lock
Labels: Type: Bug

#259 fix(FEC-9259):Smart TV detect as safari browser
  src/common/utils/setup-helpers.js
Labels: Type: Bug

#260 fix(FEC-9260): Autoplay is not working on LG TV
  src/common/utils/setup-helpers.js
Labels: Type: Bug
