Repository kaltura/kaltura-player-js, pull requests merged in 2019-06, with the labels that each got.

#240 fix(FEC-9087): IMA DAI - the pre-roll Ad duration also calculated for start position - the playback started from 10th sec instead of 20th
  src/common/utils/setup-helpers.js
Labels: Priority: High, Type: Bug

#242 fix(FEC-9177): Smart TV showed as mobile device
  src/common/ui-wrapper.js
Labels: Type: Bug

#243 fix(FEC-9118): External caption doesn't display on smart TV
  src/common/utils/setup-helpers.js
Labels: Type: Bug

#244 fix(FEC-9103): Remove old kaltura stats
  README.md
  package.json
  samples/ovp/all-plugins.html
  samples/ovp/standalone-kanalytics.html
  src/common/plugins/plugins-config-store.js
  src/index.js
  src/ott/analytics.js
  src/ovp/analytics.js
  src/ovp/player-defaults.js
  webpack.config.ott.js
  webpack.config.ovp.js
  yarn.lock
Labels: Type: Bug

#222 fix(FEC-8940): cannot configure plugin by array
  src/common/plugins/plugins-config.js
  test/src/common/plugins/plugins-config.spec.js
Labels: Priority: High, Type: Bug

#224 feat(FEC-8631): bumper plugin
  src/common/utils/setup-helpers.js
Labels: Priority: High, Type: Feature

#245 fix: bumper and ima-dai integration
  src/common/utils/setup-helpers.js
Labels: Priority: High, Type: Bug

#246 fix(FEC-9114): live doesn't work properly with hls.js on WebOS
  src/common/utils/setup-helpers.js
Labels: Type: Bug

#248 fix: inBrowserFullscreen path
  src/common/utils/setup-helpers.js
Labels: Priority: High, Type: Bug

#247 feat(FEC-9023): more logger options
  flow-typed/types/kaltura-player-options.js
  flow-typed/types/log-level.js
  package.json
  src/common/utils/logger.js
  src/common/utils/setup-helpers.js
  src/index.js
  src/setup.js
  yarn.lock
Labels: Type: Bug

#249 feat(FEC-9024): send beacon for non partner usage
  src/common/utils/setup-helpers.js
  test/src/common/utils/setup-helpers.spec.js
Labels: Type: Feature
