Repository kaltura/kaltura-player-js, pull requests merged in 2019-01, with the labels that each got.

#197 fix: set playlist by configure method doesn't work
  samples/ovp/playlist-by-config.html
  src/kaltura-player.js
  test/src/kaltura-player.spec.js
Labels: Priority: High, Type: Bug

#201 feat(FEC-8751): add support for ima playAdsAfterTime setting
  src/common/cast/remote-control.js
Labels: Priority: High, Type: Feature

#203 fix: remove applicative style
  samples/style.css
Labels: Priority: High, Type: Bug

#196 docs(FEC-8736): playlist
  docs/api.md
  docs/configuration.md
  docs/guides.md
  docs/images/playlist-countdown.png
  docs/playlist.md
  flow-typed/types/kaltura-player-event-types.js
  flow-typed/types/playlist.js
  src/kaltura-player.js
Labels: Priority: High, Type: Docs

#202 fix(FEC-8818): cast doesn't respect 'startTime' config
  src/common/cast/player-snapshot.js
Labels: Priority: High, Type: Bug

#205 feat(FEC-8661): support youtube engine playback
  src/common/utils/setup-helpers.js
  src/kaltura-player.js
  test/src/kaltura-player.spec.js
  test/src/mock-data/media.js
Labels: Type: Feature

#210 playlist - the thumbnail slices request is missing ks when the item is already played
  src/common/playlist/playlist-manager.js
Labels: Priority: High, Type: Bug

#211 fix(FEC-8842): playlist - item sources config ignored
  src/common/playlist/playlist-item.js
  src/common/playlist/playlist-manager.js
Labels: Priority: High, Type: Bug

#213 chore(FEC-8572): fix failing test
  test/src/setup.spec.js
Labels: Priority: Medium

#208 feat(FEC-8703): playlist loop
  docs/api.md
  flow-typed/types/playlist.js
  src/common/playlist/playlist-manager.js
  src/common/playlist/playlist.js
  test/src/common/playlist/playlist-manager.spec.js
  test/src/mock-data/media.js
Labels: Priority: High, Type: Feature

#209 fix(FEC-8833):playlist - no thumbnail preview when the item already played
  src/common/playlist/playlist-manager.js
Labels: Priority: High, Type: Bug

#216 docs: add references and fix links
  docs/playlist.md
Labels: Priority: High, Type: Docs

#217 fix(FEC-8871): playlist - strange behavior when playback.loop is true
  src/common/playlist/playlist-manager.js
Labels: Priority: High, Type: Bug
