Repository kaltura/kaltura-player-js, pull requests merged in 2020-12, with the labels that each got.

#386 fix(FEC-10749): playlist by sources stuck
  src/kaltura-player.js
  test/src/kaltura-player.spec.js
Labels: Priority: High, Type: Bug

#385 fix(FEC-10732, FEC-10759): player params are not injected to additional instances' config
  src/common/plugins/plugins-config-store.js
  src/common/plugins/plugins-config.js
  src/kaltura-player.js
  src/setup.js
  test/src/common/plugin/plugins-config.spec.js
  test/src/kaltura-player.spec.js
Labels: Priority: High, Type: Bug

#359 feat(FEC-10015): support smart scrubber preview and timeline marker
  docs/advertisement-layout-management.md
  docs/api.md
  docs/configuration.md
  flow-typed/types/advertising.js
  flow-typed/types/ui-component.js
  src/common/controllers/ads-controller.js
  src/common/ui-wrapper.js
Labels: Priority: High, Type: Feature

#381 fix(FEC-10729): forceRedirectExternalStreams is reset in playlist
  src/common/playlist/playlist-item.js
  src/common/playlist/playlist-manager.js
  src/common/playlist/playlist.js
  test/src/common/playlist/playlist-manager.spec.js
Labels: Priority: High

#390 fix(FEC-10806): playlist has limitation which configure cause setMedia
  src/common/playlist/playlist.js
  src/kaltura-player.js
  test/src/kaltura-player.spec.js
Labels: Type: Bug

#392 fix(FEC-10680): back-end bumper: the app should decide what bumper will be displayed when also set user bumper
  src/kaltura-player.js
Labels: Type: Bug

#393 fix(FEC-10797): back-end bumper config is left from previous media played
  src/common/playlist/playlist-item.js
  src/common/playlist/playlist-manager.js
  src/common/playlist/playlist.js
  src/common/utils/setup-helpers.js
  src/kaltura-player.js
  test/src/common/playlist/playlist-manager.spec.js
  test/src/mock-data/media.js
  test/src/mock-data/playlist.js
Labels: Type: Bug
