Repository kaltura/kaltura-player-js, pull requests merged in 2020-01, with the labels that each got.

#301 fix(FEC-9632): edge play playready on mac os when it's not supported
  src/common/utils/setup-helpers.js
Labels: Type: Bug

#298 fix(FEC-9577): Hisense TV playback doesn't work
  src/common/utils/setup-helpers.js
Labels: Type: Bug

#295 fix(FEC-9489): IE11 proxy issue in get set methods
  .babelrc
  package.json
  yarn.lock
Labels: Type: Bug

#299 feat(FEC-8998): add url encoded for referrer token
  src/common/plugins/plugins-config-store.js
  src/common/plugins/plugins-config.js
  test/src/common/plugins/plugins-config.spec.js
Labels: Type: Feature

#302 fix(FEC-9629): Player is not inline when rendered after the DOM loads
  src/common/utils/setup-helpers.js
Labels: Priority: High, Type: Bug
