Repository kaltura/kaltura-player-js, pull requests merged in 2020-11, with the labels that each got.

#374 feat(FEC-10669): add ability to pass options to loadMedia request
  docs/api.md
  docs/playing-your-video.md
  flow-typed/types/load-media-options.js
  flow-typed/types/media-config.js
  karma.conf.js
  package.json
  src/common/cast/player-snapshot.js
  src/kaltura-player.js
  test/src/kaltura-player.spec.js
  webpack.config.js
Labels: Type: Feature

#368 fix(FEC-10324): class instances merged like simple object
  package.json
  src/common/plugins/plugins-config.js
  test/src/kaltura-player.spec.js
  yarn.lock
Labels: Type: Bug

#378 fix(FEC-10694): Ima post roll overrides the post bumper
  src/common/controllers/ads-controller.js
Labels: Type: Bug

#370 feat(FEC-10656): set forceRedirectExternalStreams as true by default on IE11 and Chromecast
  src/common/utils/external-stream-redirect-helper.js
  src/common/utils/setup-helpers.js
  src/kaltura-player.js
  src/ott/player-defaults.js
  src/ovp/player-defaults.js
  test/src/ovp/player-defaults.spec.js
Labels: Priority: High, Type: Feature
