Repository kaltura/kaltura-player-js, pull requests merged in 2020-06, with the labels that each got.

#318 fix(FEC-10155): text track language is incorrect on cast disconnecting
  src/common/cast/remote-control.js
Labels: Priority: High, Type: Bug

#319 feat(FEC-9631): add support for out of band text tracks on cast sdk
  src/common/cast/remote-control.js
Labels: Priority: High, Type: Feature

#320 build: add dist to master branch on every commit for canary releases
  .travis.yml
Labels: Type: Bug

#323 build: update playkit dependencies for canary
  .travis.yml
Labels: Type: Bug
