Repository kaltura/kaltura-player-js, pull requests merged in 2020-07, with the labels that each got.

#326 fix(FEC-10122): destroy cleanup process
  src/common/playlist/playlist-manager.js
  src/common/storage/storage-manager.js
  src/kaltura-player.js
Labels: Type: Bug

#327 fix: nested TTML captions with time offset
  package.json
  yarn.lock
Labels: dependencies

#337 feat(FEC-10291): migrate analytics plugins injection from kaltura player to server
  package.json
  src/index.js
  src/ott/analytics.js
  src/ovp/analytics.js
  webpack.config.ott.js
  webpack.config.ovp.js
  yarn.lock
Labels: Priority: High

#335 feat(FEC-10290): upgrade NPM packages
  .DS_Store
  .babelrc
  .eslintrc
  .flowconfig
  .github/ISSUE_TEMPLATE.md
  .gitignore
  .prettierignore
  .travis.yml
  _config.yml
  docs/ads.md
  docs/api.md
  docs/embed-types.md
  docs/how-to-build-a-plugin.md
  docs/managing-tracks.md
  flow-typed/modules/babel-polyfill.js
  flow-typed/types/kaltura-player-event-types.js
  flow-typed/types/kaltura-player-options.js
  flow-typed/types/kaltura-player-ui-options.js
  flow-typed/types/kaltura-players.js
  flow-typed/types/log-level.js
  flow-typed/types/playlist.js
  karma.conf.js
  package.json
  scripts/job.sh
  src/common/cast/remote-player.js
  src/common/cast/text-style-convertor.js
  src/common/playlist/playlist-item.js
  src/common/plugins/plugins-config-store.js
  src/common/plugins/plugins-config.js
  src/common/polyfills/performance-now.js
  src/common/polyfills/polyfill-manager.js
  src/common/polyfills/prepend.js
  src/common/ui-wrapper.js
  src/common/utils/setup-helpers.js
  src/index.js
  test/setup/prepare-test-environment.js
  test/src/common/playlist/playlist-manager.spec.js
  test/src/common/plugins/plugins-config.spec.js
  test/src/common/storage/storage-manager.spec.js
  test/src/common/storage/storage-wrapper.spec.js
  test/src/common/utils/evaluate.spec.js
  test/src/common/utils/kaltura-params.spec.js
  test/src/common/utils/setup-helpers.spec.js
  test/src/common/utils/thumbs.spec.js
  test/src/common/utils/ui-wrapper.spec.js
  test/src/kaltura-player.spec.js
  test/src/ovp/poster.spec.js
  test/src/setup.spec.js
  webpack.config.js
  webpack.config.ott.js
  webpack.config.ovp.js
  yarn.lock
Labels: Type: Maintenance
