Repository kaltura/kaltura-player-js, pull requests merged in 2021-02, with the labels that each got.

#407 feat(FEC-10961): show the thumbnail preview in live
  src/common/utils/thumbs.js
  test/src/common/utils/thumbs.spec.js
Labels: Priority: High

#410 feat(FEC-10970): expose vpaid field on ad object
  package.json
  src/common/ads/ad.js
  yarn.lock
Labels: Priority: High, Type: Feature

#413 feat(FEC-10640): add api to get the playlist current working item index
  docs/api.md
  src/common/playlist/playlist-item.js
  src/common/playlist/playlist-manager.js
  src/common/playlist/playlist.js
  test/src/common/playlist/playlist-manager.spec.js
Labels: Priority: High, Type: Feature

#414 feat(FEC-11013): upgrade to hlsjs latest (0.14.17)
  package.json
  yarn.lock
Labels: Priority: High

#416 fix(FEC-10968): OTT doesn't have default external-stream-redirect-helper
  src/common/utils/external-stream-redirect-helper.js
  src/ott/player-defaults.js
  src/ovp/player-defaults.js
  test/src/ott/player-defaults.spec.js
Labels: Priority: High

#418 fix(FEC-11037): multiple decorator exist after destroy plugin with decorator
  src/kaltura-player.js
Labels: Type: Bug

#419 fix(FEC-11041): player fails in IE11
  src/kaltura-player.js
Labels: Priority: High, Type: Bug
